apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-service
  name: vprocache01
spec:
  ports:
  - name: db-service
    port: 3306
    protocol: TCP
    targetPort: vprodb
  selector:
   app: db
  type: ClusterIP