apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-service
  name: vprocache01
spec:
  ports:
  - name: db-service
    port: 11211
    protocol: TCP
    targetPort: mc01
  selector:
   app: memcached
  type: ClusterIP