apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vpromq01
  name: vpromq01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromq01
  template:
    metadata:
      labels:
        app: vpromq01
    spec:
      containers:
      - image: rabbitmq
        name: vpromq01
        ports:
        - name: vpromq01
          containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: secret
              key: rabbitmq
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
