apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-service
  name: vproapp
spec:
  ports:
  - name: db-service
    port: 8080
    protocol: TCP
    targetPort: app-port
  selector:
   app: vproapp
  type: LoadBalancer
